"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
#from distutils.core import setup
import py2exe
APP = ['game.py']
DATA_FILES = ['bgm.wav', 'die.wav', 'jump.wav', 'rush.wav', 'black.png', 'pill.png', 'ppx1.png',
              'ppx.png', 'ppx2.png', 'ppx_rush1.png', 'ppx_rush2.png', 'small.png', 'app.icns', 'professor.jpg',
              'professor2.jpg', 'intro.wav', 'professor.png', 'professor2.png', 'eighth_note.png', 'half_note.png',
              'quarter_note.png', 'sixteenth_note.png', 'sky2.jpg', 'thirty_second_note.png', 'whole_note.png',
              'fall_sound.wav', 'fly_sound.wav', 'jump_laugh_sound.wav', 'back.PNG', 'fla.png']
OPTIONS = {'argv_emulation':  True,
                   'iconfile':  'app.icns'}

setup(
    console=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2exe'],
)
